global:
  sendAnonymousUsage: false

entryPoints:
  web:
   address: ":80"
  db:
    address: ":5432"

api:
  insecure: true


providers:
  docker:
    network: traefik-public
    swarmMode: true

metrics:
  prometheus:
    addRoutersLabels: true