scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: traefik
    metrics_path: /metrics
    scrape_interval: 1s
    static_configs:
      - targets:
        - traefik_traefik:8080