version: '3'

services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80" # The HTTP port
      - "8080:8080" # The Web UI
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock #listen to the Docker events
  
  ws:
    image: php:8.2-apache
    volumes:
      - ./index.php:/var/www/html/index.php
    labels:
      - "traefik.http.routers.ws1.rule=Host(`localhost`)"
      - "traefik.http.services.ws.loadBalancer.sticky.cookie=true"

    deploy:
      replicas: 5
