Vagrant.configure("2") do |config|



    config.vm.define "node1" do |config|
        config.vm.box = "ubuntu/bionic64"
        config.vm.hostname = "node1"
        config.vm.provision :docker
        config.vm.provision :docker_compose
        config.vm.network "private_network", type: "static", ip: "192.168.50.11"

    end

    config.vm.define "node2" do |config|
        config.vm.box = "ubuntu/bionic64"
        config.vm.hostname = "node2"
        config.vm.provision :docker
        config.vm.network "private_network", type: "static", ip: "192.168.50.12"

    end
    
    config.vm.define "node3" do |config|
        config.vm.box = "ubuntu/bionic64"
        config.vm.hostname = "node3"
        config.vm.provision :docker
        config.vm.network "private_network", type: "static", ip: "192.168.50.13"

    end

end